name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the app
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies 
      run: npm install
    - name: Start Unit tests
      run: npm run test:unit
    - name: Show my SoftUni Username
      run: echo "myro.97"

  build-and-run-ui-tests:

    runs-on: ubuntu-latest
    needs: build-and-run-unit-tests
    steps:
    - name: Checkout the app
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies 
      run: npm install
    - name: Install playwright browsers
      run: npx playwright install
    - name: Start app before tests
      run: npm start &
    - name: Start UI tests
      run: npm run test:ui
